sudo: required
services:
  - docker

before_install:
  - docker build -t bnamita/docker-react -f Dockerfile.dev .

script:
  # -- --coverage is so that the script returns exit code 0 so that docker knows this returned without failure
  - docker run bnamita/docker-react npm run test -- --coverage
